# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.3.1

# https://circleci.com/blog/optimizing-maven-builds-on-circleci/
dependencies:
  override:
    - mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline

test:
  override:
    - mvn -o surefire:test

deployment:
  main:
    branch: master
    commands:
      - mvn -DskipTests deploy
